name: 'Get Milestones'
on:
  push
jobs:
  run-shell:
    runs-on: ubuntu-latest
    steps:
    - name: Get milestone from api endpoint
      uses: bugryn-josh/turbo-dollop/get-milestones@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
